### ISSUE TITLE
Can this module be used to install netbackup client using the install script 

### ISSUE THREAD

**Issue by SohamChakraborty** [Ericsson/puppet-module-netbackup#28]
Hi folks,

As far as I can see, this module is suited for users who have the rpm (or equivalent) packages of netbackup client. My question is can I use this module to install/manage netbackup client using the install script. Of course, I have to provide an answer file in that case, but I wanted to know whether anyone has tried something of that sort with this module. 

Thanks,

**Comment by Phil-Friderici** [comment]
Hej Soham,

there is another issue [1] that says that Veritas is releasing their own packages.
Guess it would be good to spend time on adding support for these vendor packages.
With that in place you shouldn't need any workarounds anymore.

phile grüße

[1] https://github.com/Ericsson/puppet-module-netbackup/issues/22

**Comment by SohamChakraborty** [comment]
Thanks Phil. I am not yet in a position to test vendor packages. Hopefully someone will be able to test it out. 

Cheers
